/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 12h.c                                                 *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      19                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  19                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font12h;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Font12h_0031[ 76] = { /* code 0031, DIGIT ONE */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x1C, 0xC1, 0x00,
  0x0A, 0xFF, 0xC1, 0x00,
  0x00, 0x05, 0xC1, 0x00,
  0x00, 0x05, 0xC1, 0x00,
  0x00, 0x05, 0xC1, 0x00,
  0x00, 0x05, 0xC1, 0x00,
  0x00, 0x05, 0xC1, 0x00,
  0x00, 0x05, 0xC1, 0x00,
  0x00, 0x05, 0xC1, 0x00,
  0x0A, 0xFF, 0xFF, 0xE2,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_Font12h_0032[ 76] = { /* code 0032, DIGIT TWO */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x01, 0xCF, 0xFC, 0x10,
  0x1B, 0x40, 0x0A, 0xC1,
  0x00, 0x00, 0x05, 0xE2,
  0x00, 0x00, 0x05, 0xC1,
  0x00, 0x00, 0x1C, 0x80,
  0x00, 0x00, 0xAC, 0x10,
  0x00, 0x0A, 0xC1, 0x00,
  0x00, 0xAC, 0x10, 0x00,
  0x0A, 0xA0, 0x00, 0x00,
  0x5F, 0xFF, 0xFF, 0xE2,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font12h_65F6[133] = { /* code 65F6 */
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x02, 0xC2, 0x00,
  0x5F, 0xFF, 0xE2, 0x00, 0x02, 0xC2, 0x00,
  0x5A, 0x02, 0xC2, 0x00, 0x02, 0xC2, 0x00,
  0x5A, 0x02, 0xCA, 0xFF, 0xFF, 0xFF, 0xC0,
  0x5A, 0x02, 0xC2, 0x00, 0x02, 0xC2, 0x00,
  0x5F, 0xFF, 0xE4, 0xC2, 0x02, 0xC2, 0x00,
  0x5A, 0x02, 0xC2, 0x5A, 0x02, 0xC2, 0x00,
  0x5A, 0x02, 0xC2, 0x0A, 0x52, 0xC2, 0x00,
  0x5A, 0x02, 0xC2, 0x00, 0x02, 0xC2, 0x00,
  0x5F, 0xFF, 0xE2, 0x00, 0x02, 0xC2, 0x00,
  0x5A, 0x02, 0xC2, 0x00, 0x02, 0xC2, 0x00,
  0x00, 0x00, 0x00, 0x1C, 0xFF, 0xA0, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font12h_CharInfo[3] = {
   {   8,   8,  4, acGUI_Font12h_0031 } /* code 0031 */
  ,{   8,   8,  4, acGUI_Font12h_0032 } /* code 0032 */
  ,{  13,  13,  7, acGUI_Font12h_65F6 } /* code 65F6 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font12h_Prop2 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_Font12h_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font12h_Prop1 = {
   0x0031 /* first character */
  ,0x0032 /* last character  */
  ,&GUI_Font12h_CharInfo[  0] /* address of first character */
  ,&GUI_Font12h_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font12h = {
   GUI_FONTTYPE_PROP_AA4 /* type of font    */
  ,19 /* height of font  */
  ,19 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font12h_Prop1}
  ,15 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,10 /* Height of capital characters */
};

