/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 30s.c                                                 *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      19                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  19                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font30s;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Font30s_0030[ 76] = { /* code 0030, DIGIT ZERO */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0xAF, 0xFC, 0x10,
  0x0A, 0xC1, 0x1C, 0xA0,
  0x2D, 0x40, 0x04, 0xD2,
  0x5E, 0x20, 0x02, 0xE5,
  0x5C, 0x10, 0x02, 0xE5,
  0x5C, 0x10, 0x01, 0xC5,
  0x5E, 0x20, 0x02, 0xD4,
  0x4E, 0x40, 0x04, 0xD2,
  0x0A, 0xA0, 0x1C, 0x80,
  0x01, 0xCF, 0xFA, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_Font30s_0033[ 76] = { /* code 0033, DIGIT THREE */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x01, 0xCF, 0xFA, 0x00,
  0x0A, 0x40, 0x2E, 0x80,
  0x00, 0x00, 0x0A, 0x80,
  0x00, 0x00, 0x4E, 0x40,
  0x02, 0xEF, 0xE2, 0x00,
  0x00, 0x00, 0x4F, 0x80,
  0x00, 0x00, 0x08, 0xC1,
  0x00, 0x00, 0x08, 0xC1,
  0x2A, 0x10, 0x2E, 0x80,
  0x05, 0xFF, 0xF5, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font30s_79D2[133] = { /* code 79D2 */
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x2E, 0xE2, 0x00, 0xA5, 0x00, 0x00,
  0x8F, 0xF4, 0x00, 0x00, 0xA5, 0x00, 0x00,
  0x01, 0xB4, 0x01, 0xB4, 0xA5, 0xA8, 0x00,
  0x01, 0xB4, 0x02, 0xA1, 0xA5, 0x2D, 0x40,
  0xCF, 0xFF, 0xE7, 0xA0, 0xA5, 0x04, 0xA0,
  0x04, 0xE4, 0x0A, 0x50, 0xA5, 0x00, 0x00,
  0x08, 0xFE, 0x7D, 0x40, 0xA5, 0x0A, 0x40,
  0x2D, 0xE6, 0xB4, 0x00, 0xA5, 0x8A, 0x00,
  0x89, 0xB4, 0x00, 0x00, 0x05, 0xC1, 0x00,
  0x72, 0xB4, 0x00, 0x00, 0xAC, 0x10, 0x00,
  0x01, 0xB4, 0x00, 0x8F, 0x50, 0x00, 0x00,
  0x01, 0xB4, 0xAF, 0x80, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font30s_CharInfo[3] = {
   {   8,   8,  4, acGUI_Font30s_0030 } /* code 0030 */
  ,{   8,   8,  4, acGUI_Font30s_0033 } /* code 0033 */
  ,{  13,  13,  7, acGUI_Font30s_79D2 } /* code 79D2 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font30s_Prop3 = {
   0x79D2 /* first character */
  ,0x79D2 /* last character  */
  ,&GUI_Font30s_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font30s_Prop2 = {
   0x0033 /* first character */
  ,0x0033 /* last character  */
  ,&GUI_Font30s_CharInfo[  1] /* address of first character */
  ,&GUI_Font30s_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font30s_Prop1 = {
   0x0030 /* first character */
  ,0x0030 /* last character  */
  ,&GUI_Font30s_CharInfo[  0] /* address of first character */
  ,&GUI_Font30s_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font30s = {
   GUI_FONTTYPE_PROP_AA4 /* type of font    */
  ,19 /* height of font  */
  ,19 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font30s_Prop1}
  ,15 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,10 /* Height of capital characters */
};

