/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: 48m.c                                                 *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      19                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  19                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ray_bao\Desktop\1.txt                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font48m;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Font48m_0034[ 76] = { /* code 0034, DIGIT FOUR */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0xAF, 0x40,
  0x00, 0x08, 0xEE, 0x40,
  0x00, 0x4D, 0x5E, 0x40,
  0x01, 0xB4, 0x4E, 0x40,
  0x0A, 0x80, 0x4E, 0x40,
  0x5C, 0x10, 0x4E, 0x40,
  0xCF, 0xFF, 0xFF, 0xF5,
  0x00, 0x00, 0x4E, 0x40,
  0x00, 0x00, 0x4E, 0x40,
  0x00, 0x00, 0x4E, 0x40,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_Font48m_0038[ 76] = { /* code 0038, DIGIT EIGHT */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x01, 0xCF, 0xFE, 0x20,
  0x0A, 0xA0, 0x0A, 0xC1,
  0x1C, 0x50, 0x05, 0xE2,
  0x0A, 0xC1, 0x1C, 0xA0,
  0x00, 0x8F, 0xF8, 0x00,
  0x05, 0xF8, 0x8F, 0x80,
  0x2E, 0x50, 0x04, 0xE4,
  0x4D, 0x20, 0x02, 0xE5,
  0x2E, 0x80, 0x08, 0xE2,
  0x04, 0xFF, 0xFE, 0x20,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Font48m_5206[133] = { /* code 5206 */
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0xA5, 0x1B, 0x40, 0x00, 0x00,
  0x00, 0x05, 0xC1, 0x05, 0xC1, 0x00, 0x00,
  0x00, 0x2D, 0x40, 0x01, 0xC8, 0x00, 0x00,
  0x01, 0xC5, 0x00, 0x00, 0x2E, 0x50, 0x00,
  0x2E, 0x80, 0x00, 0x00, 0x02, 0xEA, 0x00,
  0xAB, 0xFF, 0xFF, 0xFF, 0xFF, 0x5A, 0xC0,
  0x00, 0x01, 0xB4, 0x00, 0x1C, 0x50, 0x00,
  0x00, 0x02, 0xC2, 0x00, 0x1C, 0x50, 0x00,
  0x00, 0x05, 0xA0, 0x00, 0x1B, 0x40, 0x00,
  0x00, 0x2E, 0x50, 0x00, 0x2D, 0x40, 0x00,
  0x02, 0xE8, 0x00, 0x00, 0x5E, 0x20, 0x00,
  0x5F, 0x40, 0x08, 0xFF, 0xF8, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Font48m_CharInfo[3] = {
   {   8,   8,  4, acGUI_Font48m_0034 } /* code 0034 */
  ,{   8,   8,  4, acGUI_Font48m_0038 } /* code 0038 */
  ,{  13,  13,  7, acGUI_Font48m_5206 } /* code 5206 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font48m_Prop3 = {
   0x5206 /* first character */
  ,0x5206 /* last character  */
  ,&GUI_Font48m_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font48m_Prop2 = {
   0x0038 /* first character */
  ,0x0038 /* last character  */
  ,&GUI_Font48m_CharInfo[  1] /* address of first character */
  ,&GUI_Font48m_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Font48m_Prop1 = {
   0x0034 /* first character */
  ,0x0034 /* last character  */
  ,&GUI_Font48m_CharInfo[  0] /* address of first character */
  ,&GUI_Font48m_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font48m = {
   GUI_FONTTYPE_PROP_AA4 /* type of font    */
  ,19 /* height of font  */
  ,19 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Font48m_Prop1}
  ,15 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,10 /* Height of capital characters */
};

