OBJS_CONFIG += $(DIR)/core/rom/rom_rtw_message_e.o \
       $(DIR)/core/rom/rom_rtw_message_f.o \
       $(DIR)/core/rtw_ap.o \
       $(DIR)/core/rtw_debug.o \
       $(DIR)/core/efuse/rtw_efuse.o \
       $(DIR)/core/rtw_ieee80211.o \
       $(DIR)/core/rtw_intfs.o \
       $(DIR)/core/rtw_io.o \
       $(DIR)/core/rtw_ioctl_set.o \
       $(DIR)/core/rtw_mlme.o \
       $(DIR)/core/rtw_mlme_ext.o \
       $(DIR)/core/rtw_mp.o \
       $(DIR)/core/rtw_promisc.o \
       $(DIR)/core/rtw_psk.o \
       $(DIR)/core/rtw_pwrctrl.o \
       $(DIR)/core/rtw_security.o \
       $(DIR)/core/rtw_sta_mgt.o \
       $(DIR)/core/rtw_wlan_util.o \
       $(DIR)/core/rtw_suspend.o \
       $(DIR)/core/rtw_odm.o \
       $(DIR)/core/rtw_cmd.o \
       $(DIR)/core/rtw_btcoex.o \
       $(DIR)/core/rtw_btcoex_wifionly.o \
       $(DIR)/core/rtw_mi.o \
       $(DIR)/core/rtw_rf.o \
       $(DIR)/core/rtw_sae.o \
       $(DIR)/core/rtw_sae_crypto.o \
       $(DIR)/core/rtw_pmksa_cache.o \
       $(DIR)/core/option/rtw_opt_crypto_ssl.o \
       $(DIR)/core/rom/rom_rtw_wlan_util.o \
       $(DIR)/core/wifi_performance_monitor.o \
       $(DIR)/core/rtw_btcoex_soc.o \
       $(DIR)/core/rtw_ft.o \
       $(DIR)/core/rtw_rm.o \
       $(DIR)/core/rtw_rm_fsm.o \
       $(DIR)/core/rtw_rm_util.o \
       $(DIR)/core/rtw_wnm.o


OBJS_CONFIG += $(DIR)/hal/phydm/rtl8721d/halhwimg8721d_bb.o \
	$(DIR)/hal/phydm/rtl8721d/halhwimg8721d_mac.o \
	$(DIR)/hal/phydm/rtl8721d/phydm_hal_api8721d.o \
	$(DIR)/hal/phydm/rtl8721d/phydm_rtl8721d.o \
	$(DIR)/hal/phydm/rtl8721d/phydm_regconfig8721d.o

OBJS_CONFIG +=  \
	$(DIR)/hal/phydm/phydm_debug.o \
	$(DIR)/hal/phydm/phydm_dynamictxpower.o \
	$(DIR)/hal/phydm/phydm_interface.o \
	$(DIR)/hal/phydm/phydm_noisemonitor.o \
	$(DIR)/hal/phydm/phydm_pow_train.o \
	$(DIR)/hal/phydm/phydm_primary_cca.o \
	$(DIR)/hal/phydm/phydm_psd.o \
	$(DIR)/hal/phydm/phydm_rainfo.o \
	$(DIR)/hal/phydm/phydm_rssi_monitor.o \
	$(DIR)/hal/phydm/phydm.o \
	$(DIR)/hal/phydm/phydm_adaptivity.o \
	$(DIR)/hal/phydm/phydm_adc_sampling.o \
	$(DIR)/hal/phydm/phydm_api.o \
	$(DIR)/hal/phydm/phydm_ccx.o \
	$(DIR)/hal/phydm/phydm_cck_pd.o \
	$(DIR)/hal/phydm/phydm_auto_dbg.o \
	$(DIR)/hal/phydm/phydm_dig.o \
	$(DIR)/hal/phydm/phydm_dfs.o \
	$(DIR)/hal/phydm/phydm_antdect.o \
	$(DIR)/hal/phydm/phydm_hwconfig.o
	
OBJS_CONFIG += $(DIR)/hal/phydm/halrf/halrf.o \
	$(DIR)/hal/phydm/halrf/halrf_debug.o \
	$(DIR)/hal/phydm/halrf/halphyrf_iot.o \
	$(DIR)/hal/phydm/halrf/halrf_kfree.o \
	$(DIR)/hal/phydm/halrf/halrf_powertracking.o \
	$(DIR)/hal/phydm/halrf/halrf_powertracking_iot.o \
	$(DIR)/hal/phydm/halrf/halrf_txgapcal.o \
	$(DIR)/hal/phydm/halrf/rtl8721d/halrf_8721d.o \
	$(DIR)/hal/phydm/halrf/rtl8721d/halhwimg8721d_rf.o \
	$(DIR)/hal/phydm/halrf/rtl8721d/halrf_dpk_8721d.o \
	$(DIR)/hal/phydm/halrf/rtl8721d/halrf_rfk_init_8721d.o \
	$(DIR)/hal/phydm/halrf/rtl8721d/halrf_txgapk_8721d.o \

OBJS_CONFIG += $(DIR)/hal/rtl8721d/src/lx_bus/lxbus_halinit.o \
	$(DIR)/hal/rtl8721d/src/lx_bus/lxbus_ops.o \
	$(DIR)/hal/rtl8721d/src/lx_bus/lxbus_suspend.o	\
	$(DIR)/hal/rtl8721d/src/lx_bus/rtl8721d_recv.o \
	
	
OBJS_CONFIG += $(DIR)/hal/rtl8721d/src/Hal8721DPwrSeq.o \
	$(DIR)/hal/rtl8721d/src/rtl8721d_cmd.o \
	$(DIR)/hal/rtl8721d/src/rtl8721d_dm.o \
	$(DIR)/hal/rtl8721d/src/rtl8721d_firmware.o \
	$(DIR)/hal/rtl8721d/src/rtl8721d_hal_efuse.o \
	$(DIR)/hal/rtl8721d/src/rtl8721d_hal_init.o \
	$(DIR)/hal/rtl8721d/src/rtl8721d_mp.o \
	$(DIR)/hal/rtl8721d/src/rtl8721d_phycfg.o \
	$(DIR)/hal/rtl8721d/src/rtl8721d_rf6052.o \
	$(DIR)/hal/rtl8721d/src/rtl8721d_rxdesc.o \
	$(DIR)/hal/rtl8721d/src/rtl8721d_txdesc.o \
	$(DIR)/hal/rtl8721d/src/rtl8721d_btcoex.o
	
OBJS_CONFIG += $(DIR)/hal/hal_com.o \
	$(DIR)/hal/hal_com_phycfg.o \
	$(DIR)/hal/hal_intf.o \
	$(DIR)/hal/hal_phy.o  \
	$(DIR)/hal/HalPwrSeqCmd.o \
	$(DIR)/hal/hal_btcoex.o \
	$(DIR)/hal/halbtccommon.o \
	$(DIR)/hal/hal_dm.o	\
	$(DIR)/hal/hal_btcoex_wifionly.o \
	$(DIR)/hal/hal_btcoex_soc.o
	
OBJS_CONFIG +=	$(DIR)/hal/btc/halbtc8721d.o	\
	$(DIR)/hal/btc/halbtc8721dwifionly.o	\
	$(DIR)/hal/btc/halbtc8721d_phy.o	\

OBJS_CONFIG += $(DIR)/hci/hci_intfs.o \
	$(DIR)/hci/lxbus/lxbus_hci_intf.o

OBJS_CONFIG += $(DIR)/osdep/freertos/freertos_intfs.o \
	$(DIR)/osdep/freertos/freertos_ioctl.o \
	$(DIR)/osdep/freertos/freertos_mp.o \
	$(DIR)/osdep/netdev.o \

OBJS_CONFIG += $(DIR)/hal/rtl8721d/src/rom/rom_rtl8721d_hal_init.o \
	$(DIR)/hal/rtl8721d/src/rom/rom_rtl8721d_efuse.o \
	$(DIR)/hal/rtl8721d/src/rom/rom_phydm_8721d.o

OBJS_CONFIG += $(DIR)/../../../../api/wifi/wifi_simple_config_parser.o

OBJS_CONFIG += $(DIR)/../../../../bluetooth/realtek/sdk/example/bt_config/bt_config_wifi_lib.o

OBJS_CONFIG += $(DIR)/../../../../bluetooth/realtek/sdk/board/amebad/src/rtl8721d_bt_calibration.o

OBJS_CONFIG += $(DIR)/../../../../bluetooth/realtek/sdk/board/amebad/src/rtl8721d_bt.o

OBJS_CONFIG += $(DIR)/osdep/freertos/rtk_bt_if.o
